apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: web
# spec:
#   containers:
#     - name: web
#       image: web:latest
#       ports:
#         - containerPort: 5173
